# Generated by Django 5.0.6 on 2024-07-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipo_articulo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descuento', models.DecimalField(decimal_places=2, help_text='Descuento en porcentaje', max_digits=5)),
                ('precio_desc', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('smart', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('descripcion', models.CharField(default='Descripción no disponible', max_length=500)),
                ('destacado', models.BooleanField(default=False)),
                ('url', models.CharField(default='default-url', max_length=100)),
            ],
        ),
    ]
