# Generated by Django 5.0.6 on 2024-07-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.AlterField(
            model_name='item',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/static/imagenes/'),
        ),
    ]
