# Generated by Django 5.0.6 on 2024-07-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_descripcion_remove_item_destacado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
