# Generated by Django 5.0.6 on 2024-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='default-url', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.CharField(default='Descripción no disponible', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
