# Generated by Django 5.0.6 on 2024-07-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_destacado_item_url_alter_item_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
