# Generated by Django 5.0.6 on 2024-07-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_item_descripcion_item_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='default-url', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.CharField(default='Descripción no disponible', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='imagen',
            field=models.ImageField(default=2, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
